import: ~/system/system/gitlab/tanksensor-deploy.yml
stages:
  - build
  - upload

build:
  stage: build
  variables:
    TARGET: 'Tanksensor2'
  script:
    - 'echo "Starting building the project using justfile"'
    - 'cp /opt/gitlab-runner/tanksensor/.env .'
    - 'TARGET="${TARGET}" just build'
  artifacts:
    paths:
      - build/fw.zip
    expire_in: 1 month
    expose_as: 'firmware'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

upload:
  stage: upload
  script:
    - 'pwd'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/fw.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}-firmware-${CI_COMMIT_SHORT_SHA}/latest/fw.zip"'
