stages:
  - build
  - upload
  - deploy

variables:
  MOS_ARTIFACT: "build/fw.zip"

.branch-rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build:
  extends:
    - .branch-rules
  stage: build
  variables:
    TARGET: 'Tanksensor2'
  script:
    - 'echo "Starting building the project using justfile"'
    - 'cp /opt/gitlab-runner/tanksensor/.env .'
    - 'TARGET="${TARGET}" just build'
  artifacts:
    paths:
      - build/fw.zip
    expire_in: 1 month
    expose_as: 'firmware'
    reports:
      dotenv: .env

upload:
  stage: upload
  script:
    - 'pwd'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $MOS_ARTIFACT "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}-firmware-${CI_COMMIT_SHORT_SHA}/latest/fw.zip"'

deploy_to_tanksensor:
  dependencies:
    - build
  stage: deploy
  when: manual
  script:
    - 'curl -v -F file=@${MOS_ARTIFACT} http://${DEVICE_ID}/update'
